### ISSUE TITLE
Dialogs Throws Immediate Errors - Invalid print syntax for Python3, Missing version module

### ISSUE THREAD

**Issue by slowrunner** [severin-lemaignan/dialogs#1]
Installed with (no source on target):
```
$ sudo pip3 install dialogs
```

Errors:
1) Illegal print statement format for Python3 in usage() method:
   (/usr/local/bin/dialogs claims python3 - #!/usr/bin/python3)
```
dialogs -d -p "Hello"
  File "/usr/local/bin/dialogs", line 13
    print """The Dialogs natural language processor (v.""" + DIALOGS_VERSION + """).
                                                         ^
SyntaxError: invalid syntax
```

2) Package does not contain expected items if attempt to run under old Python:
```
$ python2.7 /usr/local/bin/dialogs
Traceback (most recent call last):
  File "/usr/local/bin/dialogs", line 10, in <module>
    from dialogs.version import DIALOGS_VERSION
ImportError: No module named dialogs.version
```

**Comment by severin-lemaignan** [comment]
You're forcing me to port all my Python code from 10 years ago to Python3, how mean!! 😄
I'll try to have a look in the next days!

**Comment by slowrunner** [comment]
Indeed - the expected response was: "That exercise is left for the reader" (and smarter folk than me).

There are perhaps valid positions that I should be looking to "RDF4led" or "Succinct Edge" for a lightweight triple-store (both immature), or just going full research robot architecture with Jena and ROS.  

If this turns out to be too much distraction, I will understand.

**Comment by severin-lemaignan** [comment]
There, just ported `dialogs` to Python3 (using `2to3`). The test suite mostly pass (from a cursory look, the 50 out of 300 tests that do not pass are either due to `minimalkb` not supporting some advanced reasoning, or due to incomplete `dialogs` features).
I've re-release a version `1.0` on pypi if you want to try.
